"""
╔══════════════════════════════════════════════════════════╗
║                   sybau_virus.py                         ║
║   Prank script — zero damage, 100% reversible            ║
╚══════════════════════════════════════════════════════════╝

FOLDER STRUCTURE (all in the same folder):
    sybau_virus.py
    sybau.png          ← your custom image
    ltg-sybau.mp3      ← plays when image fades in
    byebyte.wav        ← bytebeat noise (MUST be .wav)
                         generate one free at: https://bytebeat.bitforever.de/
                         or convert bytebeat2.wav with Audacity

REQUIREMENTS:
    pip install pygame pillow

TIMELINE:
    0s  — sybau.png fades into centre of a small window
    ~2s — ltg-sybau.mp3 starts playing
    ~4s — GDI effects begin cycling on the real screen + byebyte.wav joins
    ~34s— GDI effects stop, window auto-closes
    ~54s— done

GDI EFFECTS (cycle randomly via real Windows GDI / ctypes):
    1. Screen inversion / color flip
    2. Horizontal sine wobble
    3. Zoom tunnel (shrink into center)
    4. 90° rotation chunks
    5. Screen swirl (concentric ring warp)
    6. Random static / noise blocks
    7. Vertical flip strips
    8. Kaleidoscope mirror halves

NOTE: GDI effects draw directly on the Windows desktop DC —
      they are 100% temporary and vanish the moment the screen redraws.
      No files are modified. No system settings are changed.
"""

import os
import sys
import time
import ctypes
import struct
import random
import threading
import math
import wave
import io
import tkinter as tk
from tkinter import font as tkfont

try:
    from PIL import Image, ImageTk, ImageOps, ImageDraw
    PIL_OK = True
except ImportError:
    PIL_OK = False
    print("[!] pip install pillow")

try:
    import pygame
    PYGAME_OK = True
except ImportError:
    PYGAME_OK = False
    print("[!] pip install pygame")

try:
    import numpy as np
    NP_OK = True
except ImportError:
    NP_OK = False

# ─────────────────────────────────────────────────────────────────
#  PATHS
# ─────────────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

def find_file(*names):
    for name in names:
        p = os.path.join(SCRIPT_DIR, name)
        if os.path.exists(p):
            return p
    return None

IMAGE_FILE   = find_file("sybau.png", "sybau.jpg")
MP3_FILE     = find_file("ltg-sybau.mp3", "ltg-sybau.wav")
BYEBYTE_FILE = find_file("byebyte.wav")   # MUST be .wav for pygame.mixer.Sound

# ─────────────────────────────────────────────────────────────────
#  WINDOW SIZE  (small, centred, NOT fullscreen)
# ─────────────────────────────────────────────────────────────────
WIN_W = 500
WIN_H = 500

# ─────────────────────────────────────────────────────────────────
#  BYTEBEAT FALLBACK  (used only if byebyte.wav is missing)
# ─────────────────────────────────────────────────────────────────
SAMPLE_RATE = 8000

def _bytebeat2(t):
    return (t * ((t >> 12 | t >> 8) & 63)) & 0xFF

def _gen_bytebeat(duration_sec=3.0):
    n    = int(SAMPLE_RATE * duration_sec)
    data = bytes([_bytebeat2(t) & 0xFF for t in range(n)])
    buf  = io.BytesIO()
    with wave.open(buf, 'w') as wf:
        wf.setnchannels(1)
        wf.setsampwidth(1)
        wf.setframerate(SAMPLE_RATE)
        wf.writeframes(data)
    buf.seek(0)
    return buf.read()

# ─────────────────────────────────────────────────────────────────
#  AUDIO
# ─────────────────────────────────────────────────────────────────
_byebyte_sound   = None
_byebyte_channel = None

def init_audio():
    if not PYGAME_OK:
        return
    pygame.mixer.pre_init(44100, -16, 2, 512)
    pygame.mixer.init()
    pygame.mixer.set_num_channels(8)

def play_mp3():
    """Stream ltg-sybau.mp3 via pygame.mixer.music (once, no loop)."""
    if not PYGAME_OK or not MP3_FILE:
        if not MP3_FILE:
            print("[!] ltg-sybau.mp3 not found")
        return
    try:
        pygame.mixer.music.load(MP3_FILE)
        pygame.mixer.music.set_volume(1.0)
        pygame.mixer.music.play(0)
        print(f"[*] MP3: {os.path.basename(MP3_FILE)}")
    except Exception as e:
        print(f"[!] MP3 playback error: {e}")

def play_byebyte():
    """Play byebyte.wav (or generated fallback) on a separate channel, looping."""
    global _byebyte_sound, _byebyte_channel
    if not PYGAME_OK:
        return
    try:
        if BYEBYTE_FILE:
            snd = pygame.mixer.Sound(BYEBYTE_FILE)
            print(f"[*] Byebyte: {os.path.basename(BYEBYTE_FILE)}")
        else:
            print("[!] byebyte.wav not found — using generated bytebeat fallback")
            snd = pygame.mixer.Sound(buffer=_gen_bytebeat(3.0))
        snd.set_volume(1.0)
        ch = pygame.mixer.find_channel(True)
        if ch:
            ch.play(snd, loops=-1)
            _byebyte_channel = ch
            _byebyte_sound   = snd
        else:
            print("[!] No free mixer channel for byebyte")
    except Exception as e:
        print(f"[!] Byebyte error: {e}")

def stop_all_audio():
    if not PYGAME_OK:
        return
    try:
        pygame.mixer.music.stop()
    except Exception:
        pass
    try:
        pygame.mixer.stop()
    except Exception:
        pass

# ─────────────────────────────────────────────────────────────────
#  WINDOWS GDI  (real screen effects via ctypes)
# ─────────────────────────────────────────────────────────────────
user32 = ctypes.windll.user32
gdi32  = ctypes.windll.gdi32

SRCCOPY    = 0x00CC0020
SRCINVERT  = 0x00550009
HALFTONE   = 4

def _sw_sh():
    return user32.GetSystemMetrics(0), user32.GetSystemMetrics(1)

def _get_dc():
    return user32.GetDC(None)

def _rel_dc(hdc):
    user32.ReleaseDC(None, hdc)

def _make_mem(hdc, sw, sh):
    mem = gdi32.CreateCompatibleDC(hdc)
    bmp = gdi32.CreateCompatibleBitmap(hdc, sw, sh)
    gdi32.SelectObject(mem, bmp)
    return mem, bmp

def _free_mem(mem, bmp):
    gdi32.DeleteObject(bmp)
    gdi32.DeleteDC(mem)

# 1. Color inversion
def gdi_invert(sw, sh):
    hdc = _get_dc()
    gdi32.BitBlt(hdc, 0, 0, sw, sh, hdc, 0, 0, SRCINVERT)
    for _ in range(random.randint(3, 9)):
        x = random.randint(0, sw - 120)
        y = random.randint(0, sh - 120)
        w = random.randint(60, 320)
        h = random.randint(60, 220)
        gdi32.BitBlt(hdc, x, y, w, h, hdc, x, y, SRCINVERT)
    _rel_dc(hdc)

# 2. Horizontal sine wobble
_wobble_phase = 0.0
def gdi_wobble(sw, sh):
    global _wobble_phase
    hdc = _get_dc()
    mem, bmp = _make_mem(hdc, sw, sh)
    gdi32.BitBlt(mem, 0, 0, sw, sh, hdc, 0, 0, SRCCOPY)
    strip_h = 5
    for y in range(0, sh, strip_h):
        offset = int(math.sin(_wobble_phase + y * 0.025) * 28)
        gdi32.BitBlt(hdc, offset, y, sw, strip_h, mem, 0, y, SRCCOPY)
    _wobble_phase += 0.35
    _free_mem(mem, bmp)
    _rel_dc(hdc)

# 3. Zoom tunnel
def gdi_tunnel(sw, sh):
    hdc = _get_dc()
    mem, bmp = _make_mem(hdc, sw, sh)
    gdi32.BitBlt(mem, 0, 0, sw, sh, hdc, 0, 0, SRCCOPY)
    layers = random.randint(4, 7)
    for i in range(layers):
        scale = 1.0 - (i + 1) * (0.85 / layers)
        nw = int(sw * scale)
        nh = int(sh * scale)
        nx = (sw - nw) // 2
        ny = (sh - nh) // 2
        gdi32.SetStretchBltMode(hdc, HALFTONE)
        gdi32.StretchBlt(hdc, nx, ny, nw, nh, mem, 0, 0, sw, sh, SRCCOPY)
    _free_mem(mem, bmp)
    _rel_dc(hdc)

# 4. Rotation chunks (flip/mirror tiles)
def gdi_rotation_chunks(sw, sh):
    hdc = _get_dc()
    mem, bmp = _make_mem(hdc, sw, sh)
    gdi32.BitBlt(mem, 0, 0, sw, sh, hdc, 0, 0, SRCCOPY)
    tw = sw // random.randint(3, 6)
    th = sh // random.randint(3, 6)
    for ty in range(0, sh - th, th):
        for tx in range(0, sw - tw, tw):
            rot = random.choice([0, 1, 2, 3])
            if rot == 0:
                continue
            elif rot == 1:
                sx = tx + tw if tx + tw < sw else tx
                sy = ty + th if ty + th < sh else ty
                gdi32.StretchBlt(hdc, tx, ty, tw, th,
                                 mem, sx, sy, -tw, -th, SRCCOPY)
            elif rot == 2:
                gdi32.StretchBlt(hdc, tx, ty, tw, th,
                                 mem, tx + tw, ty, -tw, th, SRCCOPY)
            elif rot == 3:
                gdi32.StretchBlt(hdc, tx, ty, tw, th,
                                 mem, tx, ty + th, tw, -th, SRCCOPY)
    _free_mem(mem, bmp)
    _rel_dc(hdc)

# 5. Screen swirl (concentric ring offset)
_swirl_angle = 0.0
def gdi_swirl(sw, sh):
    global _swirl_angle
    hdc = _get_dc()
    mem, bmp = _make_mem(hdc, sw, sh)
    gdi32.BitBlt(mem, 0, 0, sw, sh, hdc, 0, 0, SRCCOPY)
    cx, cy = sw // 2, sh // 2
    ring_w = max(30, sw // 14)
    max_r  = min(cx, cy)
    for r in range(0, max_r, ring_w):
        ao = math.sin(_swirl_angle + r * 0.04) * 40
        ox = int(math.cos(math.radians(ao)) * r * 0.12)
        oy = int(math.sin(math.radians(ao)) * r * 0.12)
        x1 = max(0, cx - r - ring_w)
        y1 = max(0, cy - r - ring_w)
        x2 = min(sw, cx + r + ring_w)
        y2 = min(sh, cy + r + ring_w)
        rw, rh = x2 - x1, y2 - y1
        if rw > 0 and rh > 0:
            sx = max(0, min(sw - rw, x1 + ox))
            sy = max(0, min(sh - rh, y1 + oy))
            gdi32.BitBlt(hdc, x1, y1, rw, rh, mem, sx, sy, SRCCOPY)
    _swirl_angle += 0.2
    _free_mem(mem, bmp)
    _rel_dc(hdc)

# 6. Static noise blocks
def gdi_static(sw, sh):
    hdc = _get_dc()
    for _ in range(random.randint(30, 80)):
        x  = random.randint(0, sw - 60)
        y  = random.randint(0, sh - 40)
        w  = random.randint(5, 60)
        h  = random.randint(5, 40)
        gr = random.randint(0, 255)
        color = gr | (gr << 8) | (gr << 16)
        brush = gdi32.CreateSolidBrush(color)
        rect_bytes = struct.pack("iiii", x, y, x + w, y + h)
        ctypes.windll.user32.FillRect(
            hdc,
            ctypes.create_string_buffer(rect_bytes),
            brush
        )
        gdi32.DeleteObject(brush)
    _rel_dc(hdc)

# 7. Vertical flip strips
def gdi_vflip_strips(sw, sh):
    hdc = _get_dc()
    mem, bmp = _make_mem(hdc, sw, sh)
    gdi32.BitBlt(mem, 0, 0, sw, sh, hdc, 0, 0, SRCCOPY)
    strip_w = sw // random.randint(6, 14)
    for x in range(0, sw - strip_w, strip_w * 2):
        gdi32.StretchBlt(hdc, x, 0, strip_w, sh,
                         mem, x, sh, strip_w, -sh, SRCCOPY)
    _free_mem(mem, bmp)
    _rel_dc(hdc)

# 8. Kaleidoscope mirror
def gdi_kaleidoscope(sw, sh):
    hdc = _get_dc()
    mem, bmp = _make_mem(hdc, sw, sh)
    gdi32.BitBlt(mem, 0, 0, sw, sh, hdc, 0, 0, SRCCOPY)
    mode = random.randint(0, 3)
    hw, hh = sw // 2, sh // 2
    if mode == 0:
        gdi32.StretchBlt(hdc, sw, 0, -sw, sh, mem, 0, 0, sw, sh, SRCCOPY)
    elif mode == 1:
        gdi32.StretchBlt(hdc, 0, sh, sw, -sh, mem, 0, 0, sw, sh, SRCCOPY)
    elif mode == 2:
        gdi32.StretchBlt(hdc, hw, 0, hw, sh, mem, hw, 0, -hw, sh, SRCCOPY)
    elif mode == 3:
        gdi32.StretchBlt(hdc, 0, hh, sw, hh, mem, 0, hh, sw, -hh, SRCCOPY)
    _free_mem(mem, bmp)
    _rel_dc(hdc)

GDI_EFFECTS = [
    gdi_invert,
    gdi_wobble,
    gdi_tunnel,
    gdi_rotation_chunks,
    gdi_swirl,
    gdi_static,
    gdi_vflip_strips,
    gdi_kaleidoscope,
    gdi_tunnel,    # tunnel is extra impactful — appears twice
    gdi_swirl,
    gdi_wobble,
]

_gdi_active = False

def start_gdi_effects():
    global _gdi_active
    _gdi_active = True
    sw, sh = _sw_sh()

    def _loop():
        idx   = 0
        burst = 0
        random.shuffle(GDI_EFFECTS)
        while _gdi_active:
            try:
                GDI_EFFECTS[idx % len(GDI_EFFECTS)](sw, sh)
            except Exception:
                pass
            burst += 1
            if burst >= random.randint(6, 18):
                burst = 0
                idx  += 1
            time.sleep(0.035)   # ~28 fps

    threading.Thread(target=_loop, daemon=True).start()
    print("[*] GDI effects started.")

def stop_gdi_effects():
    global _gdi_active
    _gdi_active = False
    time.sleep(0.15)
    print("[*] GDI effects stopped.")

# ─────────────────────────────────────────────────────────────────
#  PIL IMAGE EFFECTS  (applied inside the tkinter window only)
# ─────────────────────────────────────────────────────────────────

def pil_invert(img):
    r, g, b, a = img.split()
    inv = ImageOps.invert(Image.merge("RGB", (r, g, b)))
    ir, ig, ib = inv.split()
    return Image.merge("RGBA", (ir, ig, ib, a))

def pil_sine_wobble(img):
    if not NP_OK:
        return img
    arr = np.array(img)
    h, w = arr.shape[:2]
    out  = np.zeros_like(arr)
    amp   = random.randint(8, 22)
    freq  = random.uniform(0.03, 0.09)
    phase = random.uniform(0, math.pi * 2)
    for y in range(h):
        shift = int(amp * math.sin(freq * y + phase))
        out[y] = np.roll(arr[y], shift, axis=0)
    return Image.fromarray(out, "RGBA")

def pil_zoom_tunnel(img):
    w, h  = img.size
    scale = random.uniform(0.4, 0.82)
    small = img.resize((int(w * scale), int(h * scale)), Image.LANCZOS)
    base  = img.copy()
    ox = (w - small.width)  // 2
    oy = (h - small.height) // 2
    base.paste(small, (ox, oy), small)
    return base

def pil_rotation_chunks(img):
    if not NP_OK:
        return img
    arr = np.array(img)
    h, w = arr.shape[:2]
    nx, ny = random.randint(3, 7), random.randint(3, 7)
    out = arr.copy()
    for ry in range(ny):
        for rx in range(nx):
            y0 = ry * (h // ny);  y1 = (ry+1)*(h//ny) if ry < ny-1 else h
            x0 = rx * (w // nx);  x1 = (rx+1)*(w//nx) if rx < nx-1 else w
            k  = random.choice([0, 1, 2, 3])
            chunk = np.rot90(arr[y0:y1, x0:x1], k)
            ch, cw = y1-y0, x1-x0
            if chunk.shape[0] >= ch and chunk.shape[1] >= cw:
                out[y0:y1, x0:x1] = chunk[:ch, :cw]
    return Image.fromarray(out, "RGBA")

def pil_swirl(img):
    if not NP_OK:
        return img
    arr = np.array(img, dtype=np.float32)
    h, w = arr.shape[:2]
    cx, cy = w / 2.0, h / 2.0
    strength = random.uniform(2.0, 5.0)
    ys, xs = np.mgrid[0:h, 0:w].astype(np.float32)
    dx, dy = xs - cx, ys - cy
    r   = np.sqrt(dx*dx + dy*dy)
    max_r = math.sqrt(cx*cx + cy*cy)
    angle = np.arctan2(dy, dx) + strength * (1.0 - r / (max_r + 1e-5))
    sx = np.clip((cx + r * np.cos(angle)).astype(np.int32), 0, w-1)
    sy = np.clip((cy + r * np.sin(angle)).astype(np.int32), 0, h-1)
    return Image.fromarray(arr[sy, sx].astype(np.uint8), "RGBA")

def pil_static(img):
    out  = img.copy()
    draw = ImageDraw.Draw(out)
    w, h = out.size
    for _ in range(random.randint(60, 160)):
        x  = random.randint(0, w-1)
        y  = random.randint(0, h-1)
        draw.rectangle([x, y, x+random.randint(3,55), y+random.randint(2,20)],
                       fill=(random.randint(0,255), random.randint(0,255),
                             random.randint(0,255), random.randint(120,230)))
    return out

def pil_vflip_strips(img):
    if not NP_OK:
        return img
    arr = np.array(img)
    h, w = arr.shape[:2]
    sw_  = random.randint(15, 80)
    out  = arr.copy()
    flip = False
    x = 0
    while x < w:
        x2 = min(x + sw_, w)
        if flip:
            out[:, x:x2] = arr[::-1, x:x2]
        flip = not flip
        x = x2
    return Image.fromarray(out, "RGBA")

def pil_kaleidoscope(img):
    if not NP_OK:
        return img
    arr = np.array(img)
    h, w = arr.shape[:2]
    out  = arr.copy()
    mode = random.randint(0, 3)
    if mode == 0:
        out[:, w//2:] = arr[:, :w//2][:, ::-1]
    elif mode == 1:
        out[:, :w//2] = arr[:, w//2:][:, ::-1]
    elif mode == 2:
        out[h//2:, :] = arr[:h//2, :][::-1, :]
    else:
        q = arr[:h//2, :w//2]
        out[:h//2, w//2:] = q[:, ::-1]
        out[h//2:, :w//2] = q[::-1, :]
        out[h//2:, w//2:] = q[::-1, ::-1]
    return Image.fromarray(out, "RGBA")

PIL_EFFECTS = [
    ("INVERT",        pil_invert),
    ("SINE WOBBLE",   pil_sine_wobble),
    ("ZOOM TUNNEL",   pil_zoom_tunnel),
    ("CHUNK ROTATE",  pil_rotation_chunks),
    ("SCREEN SWIRL",  pil_swirl),
    ("STATIC NOISE",  pil_static),
    ("FLIP STRIPS",   pil_vflip_strips),
    ("KALEIDOSCOPE",  pil_kaleidoscope),
]

GLITCH_CHARS = list("@#$%^&*!?░▒▓█▀▄■□☺☻♥♦♣♠◘◙×÷±§¶")

# ─────────────────────────────────────────────────────────────────
#  MAIN WINDOW APP
# ─────────────────────────────────────────────────────────────────
class SybauVirus:
    def __init__(self):
        self.root = tk.Tk()
        self.root.title("svchost.exe")
        self.root.resizable(False, False)
        self.root.overrideredirect(True)          # no title bar
        self.root.attributes("-topmost", True)

        # Centre the window on screen
        sw = self.root.winfo_screenwidth()
        sh = self.root.winfo_screenheight()
        x  = (sw - WIN_W) // 2
        y  = (sh - WIN_H) // 2
        self.root.geometry(f"{WIN_W}x{WIN_H}+{x}+{y}")
        self.root.configure(bg="black")

        self.W = WIN_W
        self.H = WIN_H

        self.canvas = tk.Canvas(
            self.root, bg="black", highlightthickness=0,
            width=self.W, height=self.H
        )
        self.canvas.pack(fill="both", expand=True)

        # State
        self.alpha        = 0.0
        self.phase        = "fade_in"
        self.frame        = 0
        self.running      = True
        self.img_tk       = None
        self.effect_frame = 0
        self.cur_effect   = PIL_EFFECTS[0]

        # Load image — fit inside WIN_W × WIN_H preserving aspect ratio
        self._base_img = None
        if PIL_OK and IMAGE_FILE:
            raw = Image.open(IMAGE_FILE).convert("RGBA")
            scale = min(WIN_W / raw.width, WIN_H / raw.height) * 0.96
            tw = int(raw.width * scale)
            th = int(raw.height * scale)
            self._base_img = raw.resize((tw, th), Image.LANCZOS)
            print(f"[+] Image: {os.path.basename(IMAGE_FILE)}  ({tw}×{th})")
        else:
            print("[!] sybau.png not found — place it next to the script.")

        # Audio init
        init_audio()
        threading.Thread(target=self._preload_byebyte, daemon=True).start()

        self.root.bind("<Escape>", lambda e: self._force_quit())
        self.root.after(300, self._tick)

    # ── AUDIO ────────────────────────────────────────────────────
    def _preload_byebyte(self):
        # Nothing to preload for MP3 — pygame.mixer.music streams it.
        # For byebyte we just call play_byebyte() when needed.
        pass

    # ── IMAGE RENDER ─────────────────────────────────────────────
    def _render_image(self, alpha=1.0, effect_fn=None):
        self.canvas.delete("img")
        if not PIL_OK or self._base_img is None:
            return
        img = self._base_img.copy()
        if effect_fn:
            try:
                img = effect_fn(img)
            except Exception:
                pass
        if alpha < 1.0:
            r, g, b, a = img.split()
            a = a.point(lambda x: int(x * alpha))
            img = Image.merge("RGBA", (r, g, b, a))
        self.img_tk = ImageTk.PhotoImage(img)
        self.canvas.create_image(
            self.W // 2, self.H // 2,
            image=self.img_tk, anchor="center", tags="img"
        )

    # ── TICK ─────────────────────────────────────────────────────
    def _tick(self):
        if not self.running:
            return
        self.frame += 1
        {
            "fade_in":  self._phase_fade_in,
            "hold":     self._phase_hold,
            "glitch":   self._phase_glitch,
            "audio2":   self._phase_audio2,
        }[self.phase]()
        self.root.after(45, self._tick)

    def _transition(self, nxt):
        self.phase, self.frame, self.effect_frame = nxt, 0, 0

    # ── PHASE 1  image fades in, MP3 starts ──────────────────────
    def _phase_fade_in(self):
        self.alpha = min(1.0, self.alpha + 0.032)
        self.canvas.delete("all")
        self._render_image(alpha=self.alpha)
        # Start MP3 when image is ~40% visible
        if self.alpha >= 0.40 and self.frame == 13:
            play_mp3()
        if self.alpha >= 1.0:
            self._transition("hold")

    # ── PHASE 2  hold & breathe ───────────────────────────────────
    def _phase_hold(self):
        pulse = 0.88 + 0.12 * math.sin(self.frame * 0.32)
        self.canvas.delete("all")
        self._render_image(alpha=pulse)
        if self.frame > 38:
            self._transition("glitch")

    # ── PHASE 3  GDI effects (real screen) + PIL effects (window)──
    def _phase_glitch(self):
        self.canvas.delete("all")
        self.effect_frame += 1

        # Start real GDI on frame 1
        if self.effect_frame == 1:
            start_gdi_effects()
            play_byebyte()

        # Switch PIL effect every ~20 frames
        if self.effect_frame == 1 or self.effect_frame % 20 == 0:
            self.cur_effect = random.choice(PIL_EFFECTS)

        name, fn = self.cur_effect
        self._render_image(alpha=1.0, effect_fn=fn)

        # Scanline rain inside the window
        for _ in range(random.randint(3, 10)):
            y   = random.randint(0, self.H)
            col = random.choice([
                "#ff0000","#00ff00","#0000ff",
                "#ffff00","#ff00ff","#00ffff","#ff8800"
            ])
            self.canvas.create_rectangle(
                0, y, self.W, y + random.randint(1, 5),
                fill=col, outline="", stipple="gray50"
            )

        if self.frame > 1000:  # ~45 seconds at 45ms/tick
            stop_gdi_effects()
            self._transition("audio2")

    # ── PHASE 4  final glitch then close ────────────────────────
    def _phase_audio2(self):
        self.canvas.delete("all")
        _, fn = self.cur_effect
        self._render_image(alpha=1.0, effect_fn=fn)

        # Scanline rain
        for _ in range(random.randint(3, 8)):
            y   = random.randint(0, self.H)
            col = random.choice(["#ff0000","#ff8800","#ffff00","#ffffff"])
            self.canvas.create_rectangle(
                0, y, self.W, y + random.randint(1, 4),
                fill=col, outline="", stipple="gray50"
            )

        if self.frame > 60:
            self.running = False
            stop_gdi_effects()
            stop_all_audio()
            self.root.after(500, self._force_quit)
            # Shut down the PC (normal shutdown — user can turn back on)
            import subprocess
            subprocess.Popen(["shutdown", "/s", "/t", "10"])  # Windows: shuts down in 10s

    # ── EXIT ─────────────────────────────────────────────────────
    def _force_quit(self):
        self.running = False
        stop_gdi_effects()
        stop_all_audio()
        try:
            self.root.destroy()
        except Exception:
            pass

    def run(self):
        self.root.mainloop()


# ─────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("=" * 55)
    print("  SYBAU FAKE VIRUS  —  zero harm, 100% prank")
    print("  Windows only (GDI effects require ctypes/Win32)")
    print("  Press ESC at any time to exit immediately.")
    print("=" * 55)
    SybauVirus().run()
    print("\nDone! You got SYBAU'd. Your computer is perfectly fine :)")